// Search-focused content for the public site, keyed by the app's river ids.
// Titles and keywords come from the October 2026 research
// (marketing/seo-research-2026-10.md): searchers use river + town names,
// "salmon run", "fishing spots", species and the year, so titles lead with those.
//
// `access` lists only well-known PUBLIC places (parks, conservation areas, public
// fishways, harbours). Never add private land or exact spots.

export const RIVER_SEO = {
  "grand-tw": { kw: "Grand River fishing", title: "Grand River Fishing: Shand Dam, Fergus & Elora Trout",
    towns: ["Fergus", "Elora", "West Montrose"], access: ["Elora Gorge Conservation Area", "Belwood Lake Conservation Area (Shand Dam)", "West Montrose"],
    hook: "Wild brown trout below Shand Dam, special catch-and-release stretches through Fergus and Elora." },
  "grand-lower": { kw: "Grand River fishing", title: "Grand River Fishing: Caledonia to Dunnville Steelhead",
    towns: ["Caledonia", "Dunnville", "Brantford"], access: ["Caledonia dam", "Byng Island Conservation Area (Dunnville)"],
    hook: "Lake Erie steelhead and lake-run browns from Caledonia to Dunnville, open to December 31 below Paris." },
  "credit-lower": { kw: "Credit River salmon run", title: "Credit River Salmon Run & Fishing in Mississauga",
    towns: ["Mississauga", "Port Credit", "Streetsville"], access: ["Erindale Park", "Port Credit harbour"],
    hook: "Chinook and steelhead in Mississauga. Open all year below Highway 403; Highway 403 to Britannia Rd closes August 15." },
  "credit-mid": { kw: "Credit River fishing", title: "Credit River Fishing: Norval & Glen Williams Trout",
    towns: ["Norval", "Glen Williams", "Georgetown"], access: ["Norval", "Glen Williams"],
    hook: "Brown and rainbow trout on the middle Credit. Season runs the fourth Saturday in April to September 30." },
  "credit-upper": { kw: "Credit River trout fishing", title: "Credit River Trout: Forks of the Credit & Belfountain",
    towns: ["Belfountain", "Caledon"], access: ["Forks of the Credit Provincial Park", "Belfountain Conservation Area"],
    hook: "Wild brook and brown trout in the upper Credit. Artificial lures and barbless hooks above Old Baseline Road." },
  "ganaraska": { kw: "Ganaraska River fishing", title: "Ganaraska River Fishing & Port Hope Salmon Run",
    towns: ["Port Hope"], access: ["Corbett Dam fishway (Port Hope fish ladder)", "Port Hope waterfront"], salmon: "port-hope-ganaraska-river",
    hook: "Port Hope's famous salmon run. Official seasons differ by stretch: one is closed all year, one closes September 1 to October 14." },
  "notty-main": { kw: "Nottawasaga River fishing", title: "Nottawasaga River Fishing: Angus to Wasaga Steelhead",
    towns: ["Angus", "Wasaga Beach", "Edenvale"], access: ["Angus", "Wasaga Beach"],
    hook: "Steelhead and Chinook from Angus to Wasaga Beach. Open all year below the Boyne River." },
  "notty-tribs": { kw: "Boyne River fishing", title: "Mad, Boyne & Pine River Trout Fishing",
    towns: ["Alliston", "Angus", "Creemore"], access: ["Earl Rowe Provincial Park (Boyne River)"],
    hook: "Cold Nottawasaga tributaries with brook and brown trout. The Boyne in Earl Rowe Park has its own closures." },
  "beaver-lower": { kw: "Beaver River fishing", title: "Beaver River Fishing at Thornbury: Steelhead & Salmon",
    towns: ["Thornbury", "Clarksburg"], access: ["Thornbury dam fishway", "Thornbury harbour"],
    hook: "Georgian Bay steelhead and salmon below the Thornbury Dam, open to December 31." },
  "beaver-upper": { kw: "Beaver River trout fishing", title: "Beaver River Trout Fishing: Kimberley to Eugenia",
    towns: ["Kimberley", "Eugenia", "Flesherton"], access: ["Eugenia Falls Conservation Area", "Kimberley"],
    hook: "Brook, brown and rainbow trout in the Beaver Valley. Season is the fourth Saturday in April to September 30." },
  "twelve-mile": { kw: "Twelve Mile Creek fishing", title: "Twelve Mile Creek Fishing: Short Hills Trout",
    towns: ["St. Catharines", "Pelham"], access: ["Short Hills Provincial Park"],
    hook: "A cold, spring-fed creek with brook and brown trout in the Short Hills near St. Catharines." },
  "bronte": { kw: "Bronte Creek fishing", title: "Bronte Creek Fishing in Oakville: Salmon & Steelhead",
    towns: ["Oakville", "Burlington"], access: ["Bronte Harbour", "Bronte Creek Provincial Park"],
    hook: "Oakville's salmon and steelhead creek. Open all year below Lakeshore Road, to December 31 up to Highway 407." },
  "sixteen": { kw: "Sixteen Mile Creek fishing", title: "Sixteen Mile Creek Fishing in Oakville: Salmon Run",
    towns: ["Oakville", "Milton"], access: ["Oakville Harbour", "Lions Valley Park"],
    hook: "Salmon and steelhead in downtown Oakville. Open all year below Lakeshore Road, to December 31 up to Highway 407." },
  "duffins": { kw: "Duffins Creek fishing", title: "Duffins Creek Fishing in Ajax & Pickering: Salmon Run",
    towns: ["Ajax", "Pickering"], access: ["Rotary Park (Ajax)", "Greenwood Conservation Area"], salmon: "duffins-creek-ajax",
    hook: "Chinook, steelhead and Atlantic salmon in Ajax and Pickering. Open all year below the CNR tracks." },
  "wilmot": { kw: "Wilmot Creek fishing", title: "Wilmot Creek Fishing in Newcastle: Salmon & Steelhead",
    towns: ["Newcastle", "Clarington", "Bowmanville"], access: ["Newcastle"],
    hook: "Steelhead, Chinook and Atlantic salmon in Newcastle. Open all year below the CNR tracks, to December 31 up to Highway 2." },
  "niagara-lower": { kw: "Niagara River fishing", title: "Lower Niagara River Fishing: Steelhead & Lake Trout",
    towns: ["Niagara Falls", "Queenston", "Niagara-on-the-Lake"], access: ["Niagara Glen", "Whirlpool", "Devil's Hole"],
    hook: "Big-water drifts for steelhead, brown trout and lake trout below the falls, in Fisheries Management Zone 20." },
  "saugeen-denny": { kw: "Saugeen River fishing", title: "Saugeen River Fishing at Denny's Dam, Southampton",
    towns: ["Southampton", "Port Elgin", "Paisley"], access: ["Denny's Dam Conservation Area", "Southampton"],
    hook: "Lake Huron steelhead and Chinook below Denny's Dam. No night fishing at the dam in October." },
  "maitland-lower": { kw: "Maitland River fishing", title: "Maitland River Fishing at Goderich: Steelhead & Salmon",
    towns: ["Goderich", "Benmiller"], access: ["Falls Reserve Conservation Area (Benmiller)", "Goderich"],
    hook: "Lake Huron steelhead and salmon from Benmiller to Goderich, open to December 31 up to County Road 4." },
  "boyne": { kw: "Boyne River fishing", title: "Boyne River Trout Fishing: Primrose Headwaters",
    towns: ["Primrose", "Shelburne", "Honeywood"], access: ["Primrose"],
    hook: "Cold Boyne River headwaters with brook and brown trout. Season is the fourth Saturday in April to September 30." },
  "humber-lower": { kw: "Humber River salmon run", title: "Humber River Salmon Run & Fishing at Old Mill",
    towns: ["Toronto", "Etobicoke"], access: ["Étienne Brûlé Park (Old Mill)", "King's Mill Park"], salmon: "humber-river-old-mill-toronto",
    hook: "Toronto's salmon run at Old Mill. The Humber is open all year for trout and salmon below Eglinton Avenue." },
  "conestogo-tw": { kw: "Conestogo River fishing", title: "Conestogo River Fishing: Tailwater Brown Trout",
    towns: ["Conestogo", "St. Jacobs", "Waterloo"], access: ["Conestogo Lake Conservation Area"],
    hook: "Cold tailwater below the Conestogo Dam with brown and rainbow trout near Waterloo." },
  "bighead": { kw: "Bighead River fishing", title: "Bighead River Fishing in Meaford: Steelhead & Salmon",
    towns: ["Meaford"], access: ["Meaford harbour"],
    hook: "Georgian Bay steelhead and Chinook in Meaford, open to December 31." },
  "sydenham-os": { kw: "Sydenham River fishing", title: "Sydenham River Fishing in Owen Sound: Salmon Run",
    towns: ["Owen Sound"], access: ["Harrison Park", "Mill Dam fishway", "Inglis Falls Conservation Area"], salmon: "owen-sound-sydenham-river",
    hook: "Owen Sound's salmon run below the Mill Dam. Sanctuaries close parts of the river; check each stretch." },
  "rouge-lower": { kw: "Rouge River fishing", title: "Rouge River Fishing in Toronto: Salmon & Steelhead",
    towns: ["Toronto", "Scarborough", "Pickering"], access: ["Rouge National Urban Park", "Rouge Beach"],
    hook: "Salmon and steelhead in Rouge National Urban Park. Open all year below Kingston Road." },
  "bowmanville": { kw: "Bowmanville Creek fishing", title: "Bowmanville Creek Fishing & Salmon Run",
    towns: ["Bowmanville", "Clarington"], access: ["Bowmanville Creek fish ladder", "Bowmanville Valley Trail"], salmon: "bowmanville-creek",
    hook: "The Bowmanville salmon run and fish ladder. Open all year below the CNR tracks, to December 31 up to Highway 2." },
  "sauble": { kw: "Sauble River fishing", title: "Sauble River Fishing: Sauble Falls Salmon & Steelhead",
    towns: ["Sauble Beach"], access: ["Sauble Falls Provincial Park"],
    hook: "Salmon and steelhead below Sauble Falls. The first 440 m below the falls is open to December 31." },
};

// Short brand suffix only where it fits Google's ~60-character title width.
export function withBrand(t) {
  for (const s of [" | Muddy York Fishing", " | Muddy York"]) if ((t + s).length <= 60) return t + s;
  return t;
}

// "Fishing spots in [town]" pages. Coordinates are town centres, used only to
// sort and measure distance to the rivers we cover.
export const TOWNS = [
  { slug: "toronto", name: "Toronto", lat: 43.6532, lon: -79.3832, title: "Fishing Spots in Toronto: Rivers for Salmon & Trout",
    local: "Toronto's rivers run right through the city: the Humber in the west end, the Don through the middle and the Rouge along the eastern edge in Rouge National Urban Park. Each fall Chinook salmon push up them from Lake Ontario, and the Humber at Old Mill is a popular place to watch the run.",
    zone: "Toronto's rivers are in Fisheries Management Zone 16. Lake Ontario and Toronto Harbour are in Zone 20." },
  { slug: "mississauga", name: "Mississauga", lat: 43.589, lon: -79.6441, title: "Fishing Spots in Mississauga: Credit River Salmon & Trout",
    local: "The Credit River runs the length of Mississauga, from Streetsville down to Port Credit and Lake Ontario. It's a busy salmon and steelhead river, and the rules change at the Highway 403 bridge and at Britannia Road.",
    zone: "The Credit River is in Fisheries Management Zone 16; Lake Ontario off Port Credit is Zone 20." },
  { slug: "oakville", name: "Oakville", lat: 43.4675, lon: -79.6877, title: "Fishing Spots in Oakville: Bronte & Sixteen Mile Creek",
    local: "Oakville has two salmon and steelhead creeks of its own: Sixteen Mile Creek, which meets the lake at Oakville Harbour, and Bronte Creek, which meets it at Bronte Harbour. Both are open all year below Lakeshore Road.",
    zone: "Both creeks are in Fisheries Management Zone 16; Lake Ontario is Zone 20." },
  { slug: "hamilton", name: "Hamilton", lat: 43.2557, lon: -79.8711, title: "Fishing Spots Near Hamilton: Trout & Steelhead Rivers",
    local: "From Hamilton you're within an easy drive of the lower Grand River at Caledonia and Dunnville, Bronte Creek in Burlington and Oakville, and the Niagara region's creeks. The lower Grand carries a steelhead run from Lake Erie each spring and fall.",
    zone: "Inland waters around Hamilton are in Fisheries Management Zone 16; Hamilton Harbour is in Zone 20." },
  { slug: "ajax-pickering", name: "Ajax and Pickering", lat: 43.8509, lon: -79.0204, title: "Fishing Spots in Ajax & Pickering: Duffins Creek Salmon",
    local: "Duffins Creek runs through Ajax and Pickering to Lake Ontario, with public access at Rotary Park in Ajax and Greenwood Conservation Area. Below the CNR tracks it's open all year for trout and salmon, and the Rouge River is just to the west.",
    zone: "Durham Region rivers are in Fisheries Management Zone 17; Lake Ontario is Zone 20." },
  { slug: "oshawa-bowmanville", name: "Oshawa and Bowmanville", lat: 43.905, lon: -78.78, title: "Fishing in Oshawa & Bowmanville: Salmon Run Creeks",
    local: "Durham's eastern creeks, Bowmanville Creek and Wilmot Creek in Newcastle, get strong fall runs of Chinook salmon and steelhead. The Bowmanville Creek fish ladder is a favourite place to watch salmon jump each September.",
    zone: "Durham Region rivers are in Fisheries Management Zone 17; Lake Ontario is Zone 20." },
  { slug: "port-hope", name: "Port Hope", lat: 43.9516, lon: -78.2928, title: "Port Hope Fishing: Ganaraska River & Salmon Run",
    local: "Port Hope is built around the Ganaraska River, home to one of Ontario's best-known salmon runs and the fish ladder at Corbett Dam. The Ganaraska has some of the province's most detailed rules: one stretch is closed all year and another closes from September 1 to October 14.",
    zone: "The Ganaraska is in Fisheries Management Zone 17; Lake Ontario is Zone 20." },
  { slug: "barrie", name: "Barrie", lat: 44.3894, lon: -79.6903, title: "Fishing Spots Near Barrie: Nottawasaga & Trout Streams",
    local: "West of Barrie, the Nottawasaga River runs from Angus to Wasaga Beach and Georgian Bay, with steelhead and Chinook salmon in spring and fall. Its cold tributaries, the Mad, Boyne and Pine rivers, hold brook and brown trout.",
    zone: "The Nottawasaga and its tributaries are in Fisheries Management Zone 16; Georgian Bay is Zone 14." },
  { slug: "owen-sound", name: "Owen Sound", lat: 44.569, lon: -80.9406, title: "Owen Sound Fishing: Sydenham River & Georgian Bay",
    local: "Owen Sound's Sydenham River runs through Harrison Park to the Mill Dam fishway and Georgian Bay, with a fall Chinook run that draws crowds. Parts of the river are sanctuaries in spring and in September, so check each stretch.",
    zone: "Rivers around Owen Sound are in Fisheries Management Zone 16; Georgian Bay is Zone 14." },
  { slug: "collingwood", name: "Collingwood", lat: 44.5008, lon: -80.2169, title: "Fishing Near Collingwood: Beaver & Bighead Rivers",
    local: "Between Collingwood and Meaford, the Beaver River at Thornbury and the Bighead River at Meaford both get Georgian Bay steelhead and salmon, open to December 31 on their lower reaches. Up the Beaver Valley, the river holds resident trout.",
    zone: "These rivers are in Fisheries Management Zone 16; Georgian Bay is Zone 14." },
  { slug: "guelph", name: "Guelph", lat: 43.5448, lon: -80.2482, title: "Fishing Near Guelph: Grand River Trout at Fergus & Elora",
    local: "North of Guelph, the Grand River below Shand Dam is a renowned brown trout tailwater, through Fergus, Elora and the Elora Gorge to West Montrose. The Conestogo tailwater near Waterloo is close by too.",
    zone: "The Grand River and the Conestogo are in Fisheries Management Zone 16." },
  { slug: "niagara", name: "Niagara Falls and St. Catharines", lat: 43.12, lon: -79.15, title: "Niagara Falls & St. Catharines Fishing: Lower Niagara",
    local: "The lower Niagara River below the falls, through the Whirlpool and Devil's Hole, is a big-water fishery for steelhead, brown trout and lake trout. Twelve Mile Creek in the Short Hills near St. Catharines is a quiet, cold trout stream by contrast.",
    zone: "The Niagara River below the falls is in Fisheries Management Zone 20; inland creeks are in Zone 16." },
];

// Where to watch the fall salmon run. `river` is the app's river id, whose
// official regulations are shown on the page.
export const SALMON_SPOTS = [
  { slug: "port-hope-ganaraska-river", river: "ganaraska", town: "port-hope", place: "Port Hope", title: "Port Hope Salmon Run & Fish Ladder (Ganaraska River)",
    h1: "Port Hope salmon run and fish ladder",
    watch: "The best-known viewing spot is the fish ladder at Corbett Dam on the Ganaraska River in Port Hope, where Chinook salmon leap the falls and climb the fishway. Bring patience: fish move in waves, often after rain.",
    rules: "The Ganaraska has three different sets of rules in Port Hope. From Highway 401 down to the Jocelyn Street bridge it's a fish sanctuary closed all year. From the Jocelyn Street bridge to the CNR tracks, no fishing is allowed from September 1 to October 14. Below the CNR tracks to Lake Ontario it's open all year for trout and salmon." },
  { slug: "humber-river-old-mill-toronto", river: "humber-lower", town: "toronto", place: "Old Mill, Toronto", title: "Humber River Salmon Run at Old Mill, Toronto",
    h1: "Humber River salmon run at Old Mill",
    watch: "In Toronto, the classic place to watch is the Humber River at Old Mill and Étienne Brûlé Park, where salmon jump the weirs on their way upstream. It's an easy walk from Old Mill subway station.",
    rules: "The Humber is open all year for Atlantic salmon, brown trout, Pacific salmon and rainbow trout from Eglinton Avenue down to Lake Ontario. Atlantic salmon must be released." },
  { slug: "bowmanville-creek", river: "bowmanville", town: "oshawa-bowmanville", place: "Bowmanville", title: "Bowmanville Salmon Run & Fish Ladder",
    h1: "Bowmanville salmon run and fish ladder",
    watch: "The fish ladder on Bowmanville Creek is one of the easiest places east of Toronto to see Chinook salmon jump. The Bowmanville Valley Trail follows the creek.",
    rules: "In Durham Region, waters below the CNR tracks are open all year for trout and salmon, and waters between Highway 2 and the CNR tracks are open to December 31." },
  { slug: "credit-river-mississauga", river: "credit-lower", town: "mississauga", place: "Mississauga", title: "Credit River Salmon Run in Mississauga",
    h1: "Credit River salmon run in Mississauga",
    watch: "Erindale Park in Mississauga is a popular place to watch salmon move up the Credit, and Port Credit at the river mouth sees fish staging in early fall.",
    rules: "Below the Highway 403 bridge the Credit is open all year for trout and salmon. From Highway 403 up to Britannia Road in Streetsville it's a fish sanctuary from August 15 to December 31, so that stretch is for watching only during the run." },
  { slug: "duffins-creek-ajax", river: "duffins", town: "ajax-pickering", place: "Ajax and Pickering", title: "Duffins Creek Salmon Run in Ajax & Pickering",
    h1: "Duffins Creek salmon run in Ajax and Pickering",
    watch: "Rotary Park in Ajax and the trails along Duffins Creek are good places to look for Chinook salmon in September and October.",
    rules: "Duffins Creek is in Durham Region: open all year for trout and salmon below the CNR tracks, and to December 31 between Highway 2 and the tracks. Above Highway 2 the zone-wide season applies and closes September 30." },
  { slug: "owen-sound-sydenham-river", river: "sydenham-os", town: "owen-sound", place: "Owen Sound", title: "Owen Sound Salmon Run: Mill Dam & Sydenham River",
    h1: "Owen Sound salmon run on the Sydenham River",
    watch: "Owen Sound's salmon gather below the Mill Dam fishway on the Sydenham River and in the river through Harrison Park, a short walk from downtown.",
    rules: "Parts of the Sydenham are sanctuaries. From the Mill Dam to 177 metres downstream is closed all year. From the base of Inglis Falls down to the line at the Chinese (Rainbow) Bridge in Harrison Park, no fishing is allowed from September 1 to 30." },
];
